2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Configure stats pid to 23664
2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-19 01:53:59,534 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_015359-r7pdnzcp\logs\debug.log
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_015359-r7pdnzcp\logs\debug-internal.log
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_init.py:init():566] calling init triggers
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'batch_size': 256, 'n_units': 41, 'learning_rate': 0.0005, 'lr_decay': 0.8456445345736732, 'lr_step': 4, 'ns': 12, 'loss': 'mse', 'update_freq': 51, 'PPO': 0, 'CQL': 0}
2024-03-19 01:53:59,535 INFO    MainThread:23664 [wandb_init.py:init():591] re-initializing run, found existing run on stack: llbficey
2024-03-19 01:53:59,536 INFO    MainThread:23664 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_Rescue_new/llbficey
2024-03-19 01:53:59,536 ERROR   MainThread:23664 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-19 01:53:59,536 INFO    MainThread:23664 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-19 01:53:59,536 INFO    MainThread:23664 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-19 01:53:59,536 INFO    MainThread:23664 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-19 01:53:59,536 INFO    MainThread:23664 [wandb_run.py:_restore():2193] restore
2024-03-19 01:53:59,536 INFO    MainThread:23664 [wandb_run.py:_restore():2199] restore done
2024-03-19 01:54:03,504 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-19 01:54:03,506 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-19 01:54:03,515 INFO    MainThread:23664 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-19 01:54:03,573 INFO    MainThread:23664 [wandb_init.py:init():616] starting backend
2024-03-19 01:54:03,573 INFO    MainThread:23664 [wandb_init.py:init():620] setting up manager
2024-03-19 01:54:03,575 INFO    MainThread:23664 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-19 01:54:03,576 INFO    MainThread:23664 [wandb_init.py:init():628] backend started and connected
2024-03-19 01:54:03,578 INFO    MainThread:23664 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-19 01:54:03,578 INFO    MainThread:23664 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-19 01:54:03,578 INFO    MainThread:23664 [wandb_init.py:init():720] updated telemetry
2024-03-19 01:54:03,602 INFO    MainThread:23664 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-19 01:54:05,040 INFO    MainThread:23664 [wandb_run.py:_on_init():2262] communicating current version
2024-03-19 01:54:05,078 INFO    MainThread:23664 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-19 01:54:05,078 INFO    MainThread:23664 [wandb_init.py:init():804] starting run threads in backend
2024-03-19 01:54:05,189 INFO    MainThread:23664 [wandb_run.py:_console_start():2241] atexit reg
2024-03-19 01:54:05,189 INFO    MainThread:23664 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-19 01:54:05,189 INFO    MainThread:23664 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-19 01:54:05,189 INFO    MainThread:23664 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-19 01:54:05,189 INFO    MainThread:23664 [wandb_init.py:init():847] run started, returning control to user process
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Configure stats pid to 23664
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-19 02:14:16,235 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_021416-j768z22a\logs\debug.log
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240319_021416-j768z22a\logs\debug-internal.log
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000202F1DE3A30>
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:init():566] calling init triggers
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'batch_size': 32, 'n_units': 3, 'learning_rate': 5e-05, 'lr_decay': 0.7465643118146577, 'lr_step': 4, 'ns': 2, 'loss': 'mse', 'update_freq': 76, 'PPO': 0, 'CQL': 0}
2024-03-19 02:14:16,237 INFO    MainThread:23664 [wandb_init.py:init():591] re-initializing run, found existing run on stack: r7pdnzcp
2024-03-19 02:14:16,238 INFO    MainThread:23664 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_Rescue_new/r7pdnzcp
2024-03-19 02:14:16,238 INFO    MainThread:23664 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-19 02:14:16,238 INFO    MainThread:23664 [wandb_run.py:_restore():2193] restore
2024-03-19 02:14:16,239 INFO    MainThread:23664 [wandb_run.py:_restore():2199] restore done
2024-03-19 02:14:20,399 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-19 02:14:20,401 INFO    MainThread:23664 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-19 02:14:20,410 INFO    MainThread:23664 [wandb_run.py:_footer_sync_info():3825] logging synced files
