2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Configure stats pid to 2396
2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Loading settings from C:\Users\CYP\.config\wandb\settings
2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Loading settings from c:\Users\CYP\Documents\GitHub\AIAKI\wandb\settings
2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-28 12:48:28,822 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240228_124828-voa1mp3y\logs\debug.log
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\CYP\Documents\GitHub\AIAKI\wandb\run-20240228_124828-voa1mp3y\logs\debug-internal.log
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001FFEBEF29B0>
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:init():566] calling init triggers
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'batch_size': 128, 'n_units': 512}
2024-02-28 12:48:28,823 INFO    MainThread:2396 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 7tcbl4yi
2024-02-28 12:48:28,824 INFO    MainThread:2396 [wandb_run.py:_finish():1970] finishing run dahs/IMV_LSTM_4hrs_mean/7tcbl4yi
2024-02-28 12:48:28,824 INFO    MainThread:2396 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-28 12:48:28,824 INFO    MainThread:2396 [wandb_run.py:_restore():2193] restore
2024-02-28 12:48:28,825 INFO    MainThread:2396 [wandb_run.py:_restore():2199] restore done
2024-02-28 12:48:33,639 INFO    MainThread:2396 [wandb_init.py:init():616] starting backend
2024-02-28 12:48:33,639 INFO    MainThread:2396 [wandb_init.py:init():620] setting up manager
2024-02-28 12:48:33,640 INFO    MainThread:2396 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-28 12:48:33,641 INFO    MainThread:2396 [wandb_init.py:init():628] backend started and connected
2024-02-28 12:48:33,643 INFO    MainThread:2396 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-28 12:48:33,643 INFO    MainThread:2396 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-28 12:48:33,643 INFO    MainThread:2396 [wandb_init.py:init():720] updated telemetry
2024-02-28 12:48:33,666 INFO    MainThread:2396 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
