



























4749it [00:59, 79.60it/s]
[W 2024-02-28 11:35:24,626] Trial 0 failed with parameters: {'batch_size': 128, 'n_units': 8, 'learning_rate': 0.0005} because of the following error: ValueError('not enough values to unpack (expected 5, got 2)').
Traceback (most recent call last):
  File "c:\Users\CYP\anaconda3\envs\torch\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_1204\1726011801.py", line 17, in objective
    auroc = train(n_units,epochs,batch_size,lr)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_1204\264482817.py", line 73, in train
    for s,a,r1,r2,r3 in val_transition:
ValueError: not enough values to unpack (expected 5, got 2)
